/*
 * Copyright (c) 2016 Hai Bison
 *
 * See the file LICENSE at the root directory of this project for copying permission.
 */

package haibison.android.underdogs;

import java.util.Calendar;
import java.util.GregorianCalendar;

/**
 * Hi  :-)
 */
public interface Underdogs {

    /**
     * Library name.
     */
    @NonNull
    String LIB_NAME = "Underdogs";

    /**
     * Library version name.
     */
    @NonNull
    String LIB_VERSION_NAME = "3.3.0";

    /**
     * Release date.
     */
    @NonNull
    Calendar RELEASE_DATE = new GregorianCalendar(2016, Calendar.OCTOBER, 13);

    /**
     * Universally unique identifier for this library, generated by Ruby  :-)
     */
    @NonNull
    String UUID = "046d8004-1727-40c3-9da4-3ba9999988cb";

    /**
     * Tag, which can be used for logging...
     */
    @NonNull
    String TAG = "UNDERDOGS_A6972EAD_" + LIB_VERSION_NAME;

}